"""
visualizations.py

Creates visualizations for loan & mortgage analysis.

Functions:
- plot_balance_over_time(df)
- plot_interest_vs_principal(df)
- plot_cumulative_interest(df)

Inputs:
df : pandas DataFrame generated by amortization.py
      Columns must include:
      ["Month", "Payment", "Interest", "Principal", "Balance"]
"""

import matplotlib.pyplot as plt


# -------------------------------------------------------------
# 1. REMAINING BALANCE OVER TIME
# -------------------------------------------------------------
def plot_balance_over_time(df, output="balance_over_time.png"):
    """
    Line chart showing how the balance reduces over the term.
    """
    plt.figure(figsize=(10, 6))
    plt.plot(df["Month"], df["Balance"], linewidth=2)

    plt.title("Remaining Loan Balance Over Time")
    plt.xlabel("Month")
    plt.ylabel("Balance ($)")
    plt.grid(True)

    plt.tight_layout()
    plt.savefig(output, dpi=200)
    plt.close()
    print(f"[Saved] {output}")


# -------------------------------------------------------------
# 2. INTEREST VS PRINCIPAL (STACKED BAR)
# -------------------------------------------------------------
def plot_interest_vs_principal(df, output="interest_vs_principal.png"):
    """
    Stacked bar chart for interest vs principal for each month.
    ⚠ Usually use head(40) for readability.
    """
    small_df = df.head(40)

    plt.figure(figsize=(12, 6))

    plt.bar(small_df["Month"], small_df["Principal"], label="Principal")
    plt.bar(
        small_df["Month"],
        small_df["Interest"],
        bottom=small_df["Principal"],
        label="Interest"
    )

    plt.title("Interest vs Principal (First 40 Months)")
    plt.xlabel("Month")
    plt.ylabel("Amount ($)")
    plt.legend()
    plt.grid(True, axis="y", linestyle="--", alpha=0.6)

    plt.tight_layout()
    plt.savefig(output, dpi=200)
    plt.close()
    print(f"[Saved] {output}")


# -------------------------------------------------------------
# 3. CUMULATIVE INTEREST CURVE
# -------------------------------------------------------------
def plot_cumulative_interest(df, output="cumulative_interest.png"):
    """
    Line chart showing how total interest accumulates over time.
    """
    df["CumulativeInterest"] = df["Interest"].cumsum()

    plt.figure(figsize=(10, 6))
    plt.plot(df["Month"], df["CumulativeInterest"], linewidth=2)

    plt.title("Cumulative Interest Over Time")
    plt.xlabel("Month")
    plt.ylabel("Cumulative Interest ($)")
    plt.grid(True)

    plt.tight_layout()
    plt.savefig(output, dpi=200)
    plt.close()
    print(f"[Saved] {output}")


# -------------------------------------------------------------
# Optional Debug Example
# -------------------------------------------------------------
if __name__ == "__main__":
    import pandas as pd
    from amortization import generate_amortization_schedule

    df = generate_amortization_schedule(200000, 0.05, 360)

    plot_balance_over_time(df)
    plot_interest_vs_principal(df)
    plot_cumulative_interest(df)
